// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp2qLxQi2ayouekuVGjy6UwB-MXvNLpV8',
    appId: '1:282287249955:web:b1483db42a4506c34f6f96',
    messagingSenderId: '282287249955',
    projectId: 'annisa-fb',
    authDomain: 'annisa-fb.firebaseapp.com',
    storageBucket: 'annisa-fb.appspot.com',
    measurementId: 'G-M4Z83L968N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2F9vuhhv4WGV1kkCvvKh1Q2yNLXrjoNA',
    appId: '1:282287249955:android:7c34a9a565a34b454f6f96',
    messagingSenderId: '282287249955',
    projectId: 'annisa-fb',
    storageBucket: 'annisa-fb.appspot.com',
  );
}
